### ISSUE TITLE
Trigger refresh

### ISSUE THREAD

**Issue by gdiazderadaa** [kartik-v/yii2-widget-typeahead#16]
Hi kartik,
Is there any way to manually trigger the refresh in the Typeahead? I have a select whose value is to be passed as parameter to the dataset query, so every time the selected value changes, the Typeahead should be refreshed.
Thanks!

**Comment by daivatsoni** [comment]
Hi Kartik,

I am also having the same issue.

I am using "remote" option for dataset, so i defintely have result set only having a characters matching with query string. but when i try to search different, it doesn't fire new ajax call, neither refresh the suggestion list. 

Tell me what can we do in this scenario.

Thank you.

**Comment by daivatsoni** [comment]
Where can i find solution for this issue?
