### ISSUE TITLE
Usage without bootstrap

### ISSUE THREAD

**Issue by yujin1st** [kartik-v/yii2-widget-typeahead#19]
Now widget requires assets that loads bootstrap.css. Even if i redeclare it, there is kartik\base\WidgetTrait that i can't override and it loads css anyway. This all means that i can't use plugin on frontend.
How can i exclude  bootstrap?

**Comment by kartik-v** [comment]
You need to use yii asset manager in your yii config file to override Asset Bundle CSS/JS settings (you need not be overriding the PHP classes in extensions for this). Read about it in yii2 docs.
