### ISSUE TITLE
Make typeahead use _POST

### ISSUE THREAD

**Issue by bologer** [kartik-v/yii2-widget-typeahead#24]
I would like to make typeahead to use `POST` requests to to the controller's action to grab the data. 

It seems that at this moment it is using `GET` and I would like to change it.

Could you please give an example of how to implement it?

**Comment by myomyintaung512** [comment]
You can use something like this below - 
```
echo $form->field($model, 'customer_id')->widget(Typeahead::classname(), [
                    'dataset' => [
                        [
                            'remote'=> [
                                'url'=>'?action=customer',
                                'prepare'=> new JsExpression(" function(query,settings) {
                                        settings.type = 'POST';
                                        settings.data:{query:query,action:'customer',otherdata:$('#otherdata').val()};
                                        return settings;
                                    }"),
                            ],
                            
                            'limit' => 10
                        ]
                    ],
                    'pluginOptions' => ['highlight' => true],
                    'options' => ['placeholder' => 'Customer ...'],
                ]); 
```

**Comment by bologer** [comment]
@myomyintaung512 could you please format your code? it is kind of unreadable a bit 

Thx for code example :+1:

**Comment by myomyintaung512** [comment]
yes, Updated

**Comment by bologer** [comment]
@myomyintaung512 , thx, I will try it ronight and write here if it worked :+1: 
Did you have similar problem?

**Comment by myomyintaung512** [comment]
Yes, I am doing now this part for my project.

**Comment by bologer** [comment]
@myomyintaung512 alright, thx for the code. Did this example work for u?

**Comment by myomyintaung512** [comment]
@bologer Yes, that's why I share my sample code here to reference for others
