### ISSUE TITLE
Accept empty array as data in TypeaheadBasic

### ISSUE THREAD

**Issue by beroso** [kartik-v/yii2-widget-typeahead#25]
There are some cases that it will be useful

**Comment by tinobreg** [comment]
I think that validating the input for an array is Ok, but maybe empty arrays could be accepted, specially for the first-time the inputs are used....

TypeaheadBasic.php on line 85 "empty($this->data)"

Regards, Martin.

**Comment by cccaballero** [comment]
I think there is a regression related to this. Empty arrays are triggering InvalidConfigException.
