### ISSUE TITLE
Getting unknown property hashVarLoadPosition

### ISSUE THREAD

**Issue by ecmciasabellano1278** [kartik-v/yii2-widget-typeahead#44]
Hi I'm getting this error

Getting unknown property hashVarLoadPosition

I'm using the latest version of this plugin.

Please help me. Thanks!

**Comment by kartik-v** [comment]
You seem to have outdated dependencies. Ensure you update via composer (and are not manually copying this extension files - as that will not work). You need the latest release of yii2-krajee-base for this extension and all Krajee extensions to work,
