### ISSUE TITLE
CSS needs adjusted to apply only to typeahead input[readonly]

### ISSUE THREAD

**Issue by darksnake747** [kartik-v/yii2-widget-typeahead#45]
I have a page that uses this widget and bootstrap 4's static control, which is an input tag set to readonly with a class of form-control-plaintext. I noticed the style of my static control was incorrect as it had a gray background. Looking at the console, I saw the style was bleeding over from the typeahead-kv.css file. 

It seems like a small oversight. I feel that this line in the current css file - `.twitter-typeahead input[disabled], input[readonly], fieldset[disabled] .twitter-typeahead input` - should be changed to this - `.twitter-typeahead input[disabled], .twitter-typeahead input[readonly], fieldset[disabled] .twitter-typeahead input`. This would better scope the styles to the intended DOM elements.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-typeahead.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/typeahead).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (typeahead) issue. (Those should be directed to the [plugin issues repo](https://github.com/typeahead/typeahead/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Add a BS4 static control to a form
2. Add this widget to the same form
3. View the form

## Expected behavior and actual behavior

When I follow those steps, I see a static control formatted similar to a readonly input field.

I was expecting to see a static control formatted as plain text.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.5.1
- yii2-widget-typeahead version: latest

## Isolating the problem

- [ ] This bug happens [on the widget demos page](http://demos.krajee.com/widget-details/typeahead)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-typeahead without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by darksnake747** [comment]
I've actually cloned the project and made the change in a new local branch, but I cannot submit a PR for it. I've read everything in this document: https://github.com/kartik-v/yii2-widget-typeahead/blob/7b7041a3cbbeb2db0a608e9f6c9b3f4f63b0069d/.github/CONTRIBUTING.md, but don't see anything I am missing that would allow me to get this change up here for review and merging. Do I need to be added first as a contributor? Sorry, I'm not the most versed in contributing to other projects like this. Let me know if there is anything I can do to get this code up here for you guys to include.

The only work around I have right now is to create some very ugly, redundant CSS to counter act the styles from this library.

**Comment by marcovtwout** [comment]
@kartik-v 1.0.5 is the latest version including this security fix, but it seems you forgot to tag the version. Here on github and on packagist its still at 1.0.4. Could you tag it and update this package on packagist?
