### ISSUE TITLE
Feature request: default suggestions option

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-widget-typeahead#5]
Can you add an option to make [default suggestions](http://twitter.github.io/typeahead.js/examples/#default-suggestions) work in `TypeaheadBasic`? Just to show full list of suggestions on input focus.

**Comment by kartik-v** [comment]
Resolved via upgrade to release v1.0.1.

**Comment by kartik-v** [comment]
Refer #6 and #7.

**Comment by RomeroMsk** [comment]
Thanks!
